# Generated by Django 5.2.3 on 2025-06-16 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('uniq', models.CharField(max_length=100, unique=True, verbose_name='Буква или номер')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('count', models.PositiveBigIntegerField(default=1, verbose_name='Счёт')),
                ('year', models.PositiveIntegerField(default=2025)),
            ],
            options={
                'verbose_name': 'Счётчик для контрактов',
                'verbose_name_plural': 'Счётчик для контрактов',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('uniq', models.CharField(blank=True, max_length=100, null=True, verbose_name='Буква или номер')),
                ('is_boss', models.BooleanField(default=False, verbose_name='Дополнительный функционал')),
                ('is_permission', models.BooleanField(default=False, verbose_name='Выходные дни')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('brand', models.ManyToManyField(to='support2_app.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('uniq', models.CharField(max_length=100, verbose_name='Буква или номер')),
                ('signature', models.TextField(verbose_name='Тип документа')),
                ('is_special', models.BooleanField(default=False, verbose_name='Спец пдф')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Сертификат')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='support2_app.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('firm', models.CharField(max_length=50, null=True, verbose_name='Название фирмы')),
                ('code', models.CharField(max_length=50, verbose_name='Номер')),
                ('status', models.BooleanField(default=True, verbose_name='Подпись')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support2_app.agent', verbose_name='Агент')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support2_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='support2_app.region'),
        ),
    ]
