# Generated by Django 5.2.3 on 2025-06-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регионы', 'verbose_name_plural': 'Регионы'},
        ),
    ]
